parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

web.config:
    validation: { enabled: true, annotations: true }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
    escaping:       htmlspecialchars

offline.config: ~

kernel.session:
    lifetime: 2592000

markdown.parser: ~      # Enable the parser service

menu.templating: ~

doctrine_user.config:
    db_driver: orm

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             array           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default
