parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

web.config:
    validation: { enabled: true, annotations: true }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
    escaping:       htmlspecialchars

offline.config: ~

kernel.session:
    lifetime: 2592000

markdown.parser: ~      # Enable the parser service

menu.templating: ~

doctrine_user.config:
    db_driver: odm

forum.config:
    db_driver: odm # can be orm or odm

doctrine_odm.mongodb:
    server: mongodb://localhost:27017
    auto_generate_proxy_classes: true
    default_database: sf2test_dev
    options:
        connect: true
