#!/usr/bin/env php
<?php

require_once __DIR__.'/MysqlKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new MysqlKernel('prod', true);

$application = new Application($kernel);
$application->run();
