#!/usr/bin/env php
<?php

require_once __DIR__.'/MongoKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new MongoKernel('dev', true);

$application = new Application($kernel);
$application->run();
